---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:  # Ensure this selector matches the labels in the template
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp  # Labels must match the selector
    spec:
      containers:
      - name: myapp
        image: merriamessam/myapp:latest
        imagePullPolicy: Always
        ports:
          containerPort: 8080
