---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind: Mapping
      name: myapp-mapping
      prefix: /myapp-endpoint  # Replace with actual endpoint if needed
      service: myapp
      weight: 100  # Replace with actual weight if needed
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: http-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:  # Ensure this selector matches the labels in the template
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp  # Labels must match the selector
    spec:
      containers:
      - name: myapp
        image: docker.io/merriamessam/myapp:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        ports:
        - name: http-api
          containerPort: 8080


